services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "4546:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PORT: 3000
      DB_HOST: ${DB_HOST:-192.168.11.68}
      DB_PORT: ${DB_PORT:-4547}
      DB_NAME: ${DB_NAME:-inventario_sistemas}
      DB_USER: ${DB_USER:-root}
      DB_PASS: ${DB_PASS:-vooez4cuefqateg8}
